# convert.py
# Converts student_model.keras → TFLite → C header for ESP32-CAM

import tensorflow as tf
import numpy as np
import os

print("=" * 55)
print("  🔧 CONVERTING MODEL FOR ESP32-CAM")
print("=" * 55)

# ========================================
# STEP 1: Load student model
# ========================================
print("\n📦 Loading student model...")
model = tf.keras.models.load_model("student_model.keras")
print(f"   ✅ Loaded ({os.path.getsize('student_model.keras')/1024:.0f} KB)")

# ========================================
# STEP 2: Create representative dataset for quantization
# ========================================
print("\n📊 Preparing calibration data...")

def representative_dataset():
    dataset = tf.keras.utils.image_dataset_from_directory(
        "dataset/train",
        image_size=(96, 96),
        batch_size=1,
        label_mode=None,
        shuffle=True,
        seed=42
    )
    for image_batch in dataset.take(200):
        image = tf.cast(image_batch, tf.float32) / 255.0
        yield [image.numpy()]

# ========================================
# STEP 3: Convert to TFLite with INT8 quantization
# ========================================
print("\n🔧 Converting to TFLite (INT8 quantized)...")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

# Save TFLite
tflite_path = "animal_model.tflite"
with open(tflite_path, "wb") as f:
    f.write(tflite_model)

tflite_size = os.path.getsize(tflite_path)
print(f"   ✅ TFLite model: {tflite_size/1024:.1f} KB")

# ========================================
# STEP 4: Check if it fits ESP32
# ========================================
if tflite_size < 500_000:
    print(f"   ✅ Fits on ESP32-CAM! (< 500KB)")
elif tflite_size < 1_000_000:
    print(f"   ⚠️  Tight fit but should work (< 1MB)")
else:
    print(f"   ❌ Too large for ESP32! Need to shrink model.")

# ========================================
# STEP 5: Convert to C header file
# ========================================
print("\n📝 Generating C header file...")

with open("animal_model.h", "w") as f:
    f.write("// Auto-generated by convert.py\n")
    f.write("// WildEdge AI — Animal Detection Model for ESP32-CAM\n")
    f.write(f"// Model size: {tflite_size} bytes ({tflite_size/1024:.1f} KB)\n")
    f.write(f"// Input: 96x96x3 INT8 | Output: 8-class INT8\n\n")
    f.write("#ifndef ANIMAL_MODEL_H\n")
    f.write("#define ANIMAL_MODEL_H\n\n")
    f.write(f"const unsigned int model_len = {tflite_size};\n")
    f.write("alignas(8) const unsigned char model_data[] = {\n")
    
    with open(tflite_path, "rb") as tf_file:
        content = tf_file.read()
    
    for i in range(0, len(content), 12):
        chunk = content[i:i+12]
        hex_str = ", ".join([f"0x{b:02x}" for b in chunk])
        f.write(f"  {hex_str},\n")
    
    f.write("};\n\n")
    f.write("#endif  // ANIMAL_MODEL_H\n")

header_size = os.path.getsize("animal_model.h")
print(f"   ✅ C header: animal_model.h ({header_size/1024:.1f} KB)")

# ========================================
# STEP 6: Verify by loading TFLite model
# ========================================
print("\n🧪 Verifying TFLite model...")

interpreter = tf.lite.Interpreter(model_path=tflite_path)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(f"   Input:  shape={input_details[0]['shape']} dtype={input_details[0]['dtype']}")
print(f"   Output: shape={output_details[0]['shape']} dtype={output_details[0]['dtype']}")

# Quick test
with open("class_names.txt") as f:
    CLASS_NAMES = [l.strip() for l in f]

test_ds = tf.keras.utils.image_dataset_from_directory(
    "dataset/validation", image_size=(96,96), batch_size=1,
    label_mode='categorical', shuffle=True, seed=99
)

correct = 0
total = 0

for img, lbl in test_ds.take(50):
    img_int8 = tf.cast(img / 255.0 * 255 - 128, tf.int8).numpy()
    interpreter.set_tensor(input_details[0]['index'], img_int8)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])
    
    pred = np.argmax(output)
    actual = np.argmax(lbl[0])
    if pred == actual:
        correct += 1
    total += 1

tflite_acc = correct / total * 100
print(f"\n   TFLite accuracy: {tflite_acc:.1f}% (on 50 validation images)")

# ========================================
# SUMMARY
# ========================================
keras_size = os.path.getsize("student_model.keras") / 1024

print(f"\n{'='*55}")
print(f"  ✅ CONVERSION COMPLETE")
print(f"{'='*55}")
print(f"  Keras model:   {keras_size:.0f} KB")
print(f"  TFLite model:  {tflite_size/1024:.1f} KB")
print(f"  C header:      {header_size/1024:.1f} KB")
print(f"  Compression:   {keras_size/(tflite_size/1024):.1f}x")
print(f"  TFLite acc:    {tflite_acc:.1f}%")
print(f"{'='*55}")
print(f"\n  Files ready for ESP32:")
print(f"    animal_model.h    ← #include this in Arduino sketch")
print(f"    animal_model.tflite ← for testing on PC")
print(f"\n  次: Flash to ESP32-CAM using Arduino IDE")